
// Generated by CodiumAI

import org.exploration.sinks.MemorySink;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class MemorySinkTest {


    // Can add a single string to memory list using output method
    @Test
    public void test_add_single_string_to_memory_list() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        memorySink.output("Hello");
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertEquals(1, memory.size());
        assertEquals("Hello", memory.get(0));
    }

    // Can add multiple strings to memory list using output method
    @Test
    public void test_add_multiple_strings_to_memory_list() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        memorySink.output("Hello");
        memorySink.output("World");
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertEquals(2, memory.size());
        assertEquals("Hello", memory.get(0));
        assertEquals("World", memory.get(1));
    }

    // Memory list is empty when no strings have been added
    @Test
    public void test_memory_list_is_empty_when_no_strings_added() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertTrue(memory.isEmpty());
    }

    // Memory list contains all strings added using output method
    @Test
    public void test_memory_list_contains_all_strings_added() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        memorySink.output("Hello");
        memorySink.output("World");
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertEquals(2, memory.size());
        assertTrue(memory.contains("Hello"));
        assertTrue(memory.contains("World"));
    }

    // Memory list maintains order of strings added using output method
    @Test
    public void test_memory_list_maintains_order_of_strings_added() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        memorySink.output("Hello");
        memorySink.output("World");
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertEquals(2, memory.size());
        assertEquals("Hello", memory.get(0));
        assertEquals("World", memory.get(1));
    }

    // Memory list can handle large number of strings added using output method
    @Test
    public void test_memory_list_can_handle_large_number_of_strings_added() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        for (int i = 0; i < 100000; i++) {
            memorySink.output("String " + i);
        }
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertEquals(100000, memory.size());
    }

    // Memory list remains unchanged when null is passed to output method
    @Test
    public void test_memory_list_remains_unchanged_when_null_passed() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        memorySink.output(null);
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertTrue(memory.isEmpty());
    }

    // Memory list remains unchanged when empty list is passed to output method
    @Test
    public void test_memory_list_remains_unchanged_when_empty_list_passed() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        memorySink.output("");
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertTrue(memory.isEmpty());
    }

    // Memory list remains unchanged when list with null is passed to output method
    @Test
    public void test_memory_list_remains_unchanged_when_list_with_null_passed() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        List<String> list = new ArrayList<>();
        list.add(null);
        memorySink.output(list);
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertTrue(memory.isEmpty());
    }

    // Memory list remains unchanged when list with empty string is passed to output method
    @Test
    public void test_memory_list_remains_unchanged_when_list_with_empty_string_passed() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        List<String> list = new ArrayList<>();
        list.add("");
        memorySink.output(list);
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertTrue(memory.isEmpty());
    }

    // Memory list remains unchanged when list with null and empty string is passed to output method
    @Test
    public void test_memory_list_remains_unchanged_when_list_with_null_and_empty_string_passed() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        List<String> list = new ArrayList<>();
        list.add(null);
        list.add("");
        memorySink.output(list);
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertTrue(memory.isEmpty());
    }

    // Memory list can handle long strings added using output method
    @Test
    public void test_memory_list_can_handle_long_strings_added() {
        // Given
        MemorySink memorySink = new MemorySink();
    
        // When
        memorySink.output("This is a very long string that exceeds the normal length of a string");
    
        // Then
        List<String> memory = memorySink.getMemory();
        assertEquals(1, memory.size());
        assertEquals("This is a very long string that exceeds the normal length of a string", memory.get(0));
    }

}